---
  roles:
    - name: geerlingguy.dockerm
      version: 4.1.3
    - name: christiangda.awscli
      version: 1.0.2
    - name: christiangda.awscli_configure
      version: 0.0.5
    - name: diodonfrost.terraform
      vesion: 1.6.1